version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "$PWD/data/redis:/data"
  app:
    build:
      context: .
      dockerfile: $PWD/docker/golang/Dockerfile
    ports:
      - "8080:8080"
    tty:
       true
    volumes:
      - $PWD:/go/src/app
    environment:
      RADIS_HOST: redis
      RADIS_PORT: 6379
      NAMEAPACE: "test_radis"
      PROJECTID: ${PROJECTID}
      CREDENTIALS: ${CREDENTIALS}
    command: go run application/redis/main.go

